table DimEducationLevel
	lineageTag: 9365378b-0420-4656-b0ab-67969f84e71a

	column EducationLevelID
		dataType: int64
		formatString: 0
		lineageTag: 5b41a4d1-4b77-4bb4-b640-a743b4167bfc
		summarizeBy: none
		sourceColumn: EducationLevelID

		annotation SummarizationSetBy = Automatic

	column EducationLevel
		dataType: string
		lineageTag: 20e4f4c0-4bf9-4be4-9961-065bdac0edd0
		summarizeBy: none
		sourceColumn: EducationLevel

		annotation SummarizationSetBy = Automatic

	partition DimEducationLevel-5e7f9a7e-ffaf-424a-8f01-1bd655130072 = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://assets.datacamp.com/production/repositories/6064/datasets/48c153f648e330fad41674c71802f64b64f94598/EducationLevel.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EducationLevelID", Int64.Type}, {"EducationLevel", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

