table ___Measures
	lineageTag: e87f962b-7953-4351-be0c-e1734d05cfbf

	measure TotalGames = DISTINCTCOUNT(Grouped[App ID])
		formatString: 0
		lineageTag: 8fe2b0f3-c9e3-4c9e-9259-19d0db55e966

	measure TotalPublishers = DISTINCTCOUNT(Grouped[Publisher])
		formatString: 0
		lineageTag: 70bdeb5c-e106-4cac-9812-2b80441c7d0b

	measure TotalDevelopers = DISTINCTCOUNT(Grouped[Developer])
		formatString: 0
		lineageTag: b2d58964-74ac-42aa-b64d-991f43ae9e97

	measure AVGPrice = AVERAGE(Grouped[FixedPrice])
		formatString: 0
		lineageTag: 52040c5c-7edc-4492-b1e1-4960d6f69bbd

	measure PurchasedReviewers =
			
			CALCULATE(
			    COUNTROWS(Dim_Reviews_View),
			    Dim_Reviews_View[steam_purchase] = TRUE()
			)
		formatString: 0
		lineageTag: f5506d3f-315f-4fcb-8119-c746ecee88dc

	column Column
		formatString: 0
		lineageTag: 1f5d308b-ca3a-41f9-82fc-d010bd830492
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition ___Measures = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = f83bbbfa96d247488f5776c6fc11fd26

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

