table _Measures
	lineageTag: 97280750-dfeb-4ea4-9563-2691a33670d4

	measure 'Total Games' = DISTINCTCOUNT(Dim_Applications_View[Game])
		formatString: 0
		lineageTag: 33eb74d0-371f-489b-a287-a2156af14692

	measure 'Total Developers' = DISTINCTCOUNT(Dim_Developers_View[Developer])
		formatString: 0
		lineageTag: b0bd5078-dacf-4ee0-9dc5-82d3931d0bf7

	measure 'Total Publishers' = DISTINCTCOUNT(Dim_Publishers_View[Publisher])
		formatString: 0
		lineageTag: f23d7e8d-e5ec-4957-8b5e-3eaae7871951

	measure 'Metacritic Max' = 100
		formatString: 0
		lineageTag: 8a0a1955-2e32-4d8a-b92d-f7d8d60fba9b

	measure Total = DISTINCTCOUNT(Dim_Applications_View[App ID])
		formatString: 0
		lineageTag: 5cf6d581-e5d8-4029-a41d-4b09b6dbb2eb

	measure 'Unique App Count' = ```
			
			CALCULATE(
			    DISTINCTCOUNT('Fact_Applications_View'[App ID]),
			    ALL('Fact_Applications_View') 
			)
			```
		formatString: 0
		lineageTag: 8190a60d-12b8-454c-b79e-6c5aa54d7f3c

	column Column
		formatString: 0
		lineageTag: 0aaf6258-b6e6-4aee-ae7a-830ad4ad8e07
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Measures = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 5de99ff6a6b3431d9b632e2189264858

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

