table Dim_Categories_View
	lineageTag: 96241103-fae3-4429-a83c-f2ddc3ee188b

	column appid
		dataType: int64
		formatString: 0
		lineageTag: c09cb76c-393f-445e-aaaa-f653833cf2c8
		summarizeBy: none
		sourceColumn: appid

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: cac8c81a-02d4-4eed-8977-08b76e96dd59
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition Dim_Categories_View = m
		mode: import
		source =
				let
				    Source = Sql.Database("DESKTOP-M9MOB75\SQLEXPRESS", "Steam"),
				    dbo_Dim_Categories_View = Source{[Schema="dbo",Item="Dim_Categories_View"]}[Data],
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(dbo_Dim_Categories_View, {{"Categories", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "Categories"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Categories", type text}}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"appid"}, "Attribute", "Value"),
				    #"Added Custom" = Table.AddColumn(#"Unpivoted Other Columns", "Flag", each 1),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"Flag", "Attribute"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

