table Fact_Applications_View
	lineageTag: 9a680da0-707a-4db4-8d86-346c34fd2750

	column 'App ID'
		dataType: int64
		formatString: 0
		lineageTag: 573fc198-4b4e-4d9d-9cc5-00bd438e323b
		summarizeBy: none
		sourceColumn: App ID

		annotation SummarizationSetBy = Automatic

	column 'Release Date'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 50e0f8cc-f508-4f4a-983f-225272e9cf82
		summarizeBy: none
		sourceColumn: Release Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Price
		dataType: double
		formatString: 0
		lineageTag: 186ec20f-bba7-427d-b82e-9e3eb4a55ef3
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

	column 'Required Age'
		dataType: int64
		formatString: 0
		lineageTag: 336933ca-3b9c-41d2-9e7f-04b246706e04
		summarizeBy: sum
		sourceColumn: Required Age

		annotation SummarizationSetBy = Automatic

	column 'Metacritic Score'
		dataType: int64
		formatString: 0
		lineageTag: 4c62431e-011d-4331-b4e8-c3569f27abfe
		summarizeBy: sum
		sourceColumn: Metacritic Score

		annotation SummarizationSetBy = Automatic

	column 'Recommendations Total'
		dataType: int64
		formatString: 0
		lineageTag: a5d1da56-839b-4260-861e-7558594b40ef
		summarizeBy: sum
		sourceColumn: Recommendations Total

		annotation SummarizationSetBy = Automatic

	column FixedPrice
		dataType: string
		lineageTag: 720328da-8a51-464f-a76f-b8507cad3fee
		summarizeBy: none
		sourceColumn: FixedPrice

		annotation SummarizationSetBy = Automatic

	column 'Price Range'
		dataType: string
		lineageTag: 745bce12-cb87-4f09-a99a-bbbb01dd158c
		summarizeBy: none
		sourceColumn: Price Range

		annotation SummarizationSetBy = Automatic

	column Year = YEAR('Fact_Applications_View'[Release Date])
		formatString: 0
		lineageTag: 8bac86bf-f656-4a67-bc8e-89290255f898
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Fact_Applications_View = m
		mode: import
		source =
				let
				    Source = Sql.Database("DESKTOP-M9MOB75\SQLEXPRESS", "Steam"),
				    dbo_Fact_Applications_View = Source{[Schema="dbo",Item="Fact_Applications_View"]}[Data],
				    #"Divided Column" = Table.TransformColumns(dbo_Fact_Applications_View, {{"Price", each _ / 100, type number}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Divided Column",null,0,Replacer.ReplaceValue,{"Price"}),
				    #"Added Custom" = Table.AddColumn(#"Replaced Value", "FixedPrice", each if [Price] >= 100000 then [Price] / 100000
				  else if [Price] >= 10000 then [Price] / 10000
				  else if [Price] >= 1000 then [Price] / 1000
				  else if [Price] >= 100 then [Price] / 100
				  else [Price]),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Price Range", each if [Price] = 0 then "Free"
				  else if [Price] > 0 and [Price] <= 9.99 then "0.01$ - 9.99$"
				  else if [Price] >= 10 and [Price] <= 19.99 then "10$ - 19.99$"
				  else if [Price] >= 20 and [Price] <= 29.99 then "20$ - 29.99$"
				  else if [Price] >= 30 and [Price] <= 39.99 then "30$ - 39.99$"
				  else if [Price] >= 40 and [Price] <= 49.99 then "40$ - 49.99$"
				  else if [Price] >= 50 and [Price] <= 59.99 then "50$ - 59.99$"
				  else if [Price] >= 60 and [Price] <= 69.99 then "60$ - 69.99$"
				  else if [Price] >= 70 and [Price] <= 79.99 then "70$ - 79.99"
				  else if [Price] >= 80 and [Price] <= 89.99 then "80$ - 89.99$"
				  else if [Price] >= 90 and [Price] <= 99.99 then "90$ - 99.99$"
				  else "100$+")
				in
				    #"Added Custom1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

