table Grouped
	lineageTag: a4de9bfe-2020-4635-88f0-2feaf5dc9a60

	column 'App ID'
		dataType: int64
		formatString: 0
		lineageTag: c425ead5-4d60-4ad1-a894-cc1263a12dd2
		summarizeBy: none
		sourceColumn: App ID

		annotation SummarizationSetBy = Automatic

	column 'Release Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 243c9b40-b374-4101-b3b7-aefb30b98bef
		summarizeBy: none
		sourceColumn: Release Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Price
		dataType: double
		lineageTag: 57ffedf2-08ca-4c36-80cd-d8417d341598
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Required Age'
		dataType: int64
		formatString: 0
		lineageTag: 6f91edb4-c136-4093-9093-8aabe6919014
		summarizeBy: sum
		sourceColumn: Required Age

		annotation SummarizationSetBy = Automatic

	column 'Metacritic Score'
		dataType: int64
		formatString: 0
		lineageTag: 12cc0091-e2be-4413-8994-408eaecbef94
		summarizeBy: sum
		sourceColumn: Metacritic Score

		annotation SummarizationSetBy = Automatic

	column 'Recommendations Total'
		dataType: int64
		formatString: 0
		lineageTag: 07d6009b-7b83-4951-b457-4ea4a3f825de
		summarizeBy: sum
		sourceColumn: Recommendations Total

		annotation SummarizationSetBy = Automatic

	column FixedPrice
		dataType: string
		lineageTag: 7197f3ff-151f-4f92-a1df-12a7e9f33c5d
		summarizeBy: none
		sourceColumn: FixedPrice

		annotation SummarizationSetBy = Automatic

	column 'Price Range'
		dataType: string
		lineageTag: 6e9be007-dd98-46ad-8f61-b511eedf8b4e
		summarizeBy: none
		sourceColumn: Price Range

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: e190637e-9eab-416b-b793-f40d59e1bef7
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Is Free'
		dataType: string
		lineageTag: ae696c8b-533e-4f46-b60f-fb3c5e339877
		summarizeBy: none
		sourceColumn: Is Free

		annotation SummarizationSetBy = Automatic

	column 'Price Category'
		dataType: string
		lineageTag: 1e8de842-9607-4e09-8ad7-dae057773d5b
		summarizeBy: none
		sourceColumn: Price Category

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 8cc81144-7968-4b4d-bd37-3c1ffd284fca
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Flag
		dataType: string
		lineageTag: 060f25a7-d40b-448d-a411-533af9280ec5
		summarizeBy: none
		sourceColumn: Flag

		annotation SummarizationSetBy = Automatic

	column Developer
		dataType: string
		lineageTag: b2b7d017-e981-4a3e-9ecd-9adc1a69cef4
		summarizeBy: none
		sourceColumn: Developer

		annotation SummarizationSetBy = Automatic

	column Genre
		dataType: string
		lineageTag: ddda36ea-6fca-4919-98a0-8f441aa50732
		summarizeBy: none
		sourceColumn: Genre

		annotation SummarizationSetBy = Automatic

	column Platform
		dataType: string
		lineageTag: c1915889-734b-4da4-8d8e-ef98a96c1e03
		summarizeBy: none
		sourceColumn: Platform

		annotation SummarizationSetBy = Automatic

	column Publisher
		dataType: string
		lineageTag: 2634d78a-3150-4002-b576-540d406d28b4
		summarizeBy: none
		sourceColumn: Publisher

		annotation SummarizationSetBy = Automatic

	column Year = YEAR('Grouped'[Release Date])
		formatString: 0
		lineageTag: 133e069f-260d-42f4-adb0-1be6069e5bdf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Grouped = m
		mode: import
		source =
				let
				    Source = Sql.Database("DESKTOP-M9MOB75\SQLEXPRESS", "Steam"),
				    dbo_Fact_Applications_View = Source{[Schema="dbo",Item="Fact_Applications_View"]}[Data],
				    #"Divided Column" = Table.TransformColumns(dbo_Fact_Applications_View, {{"Price", each _ / 100, type number}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Divided Column",null,0,Replacer.ReplaceValue,{"Price"}),
				    #"Added Custom" = Table.AddColumn(#"Replaced Value", "FixedPrice", each if [Price] >= 100000 then [Price] / 100000
				  else if [Price] >= 10000 then [Price] / 10000
				  else if [Price] >= 1000 then [Price] / 1000
				  else if [Price] >= 100 then [Price] / 100
				  else [Price]),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Price Range", each if [Price] = 0 then "Free"
				  else if [Price] > 0 and [Price] <= 9.99 then "0.01$ - 9.99$"
				  else if [Price] >= 10 and [Price] <= 19.99 then "10$ - 19.99$"
				  else if [Price] >= 20 and [Price] <= 29.99 then "20$ - 29.99$"
				  else if [Price] >= 30 and [Price] <= 39.99 then "30$ - 39.99$"
				  else if [Price] >= 40 and [Price] <= 49.99 then "40$ - 49.99$"
				  else if [Price] >= 50 and [Price] <= 59.99 then "50$ - 59.99$"
				  else if [Price] >= 60 and [Price] <= 69.99 then "60$ - 69.99$"
				  else if [Price] >= 70 and [Price] <= 79.99 then "70$ - 79.99"
				  else if [Price] >= 80 and [Price] <= 89.99 then "80$ - 89.99$"
				  else if [Price] >= 90 and [Price] <= 99.99 then "90$ - 99.99$"
				  else "100$+"),
				    #"Merged Queries" = Table.NestedJoin(#"Added Custom1", {"App ID"}, Dim_Applications_View, {"App ID"}, "Dim_Applications_View", JoinKind.LeftOuter),
				    #"Expanded Dim_Applications_View" = Table.ExpandTableColumn(#"Merged Queries", "Dim_Applications_View", {"Type", "Is Free", "Price Category"}, {"Type", "Is Free", "Price Category"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded Dim_Applications_View", {"App ID"}, Dim_Categories_View, {"appid"}, "Dim_Categories_View (3)", JoinKind.LeftOuter),
				    #"Expanded Dim_Categories_View (3)" = Table.ExpandTableColumn(#"Merged Queries1", "Dim_Categories_View (3)", {"Attribute", "Value", "Flag"}, {"Attribute", "Value", "Flag"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded Dim_Categories_View (3)",{"Attribute"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Value", "Category"}}),
				    #"Merged Queries2" = Table.NestedJoin(#"Renamed Columns", {"App ID"}, Dim_Developers_View, {"App ID"}, "Dim_Developers_View", JoinKind.LeftOuter),
				    #"Expanded Dim_Developers_View" = Table.ExpandTableColumn(#"Merged Queries2", "Dim_Developers_View", {"Developer"}, {"Developer"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Expanded Dim_Developers_View", {"App ID"}, Dim_Genres_View, {"App ID"}, "Dim_Genres_View", JoinKind.LeftOuter),
				    #"Expanded Dim_Genres_View" = Table.ExpandTableColumn(#"Merged Queries3", "Dim_Genres_View", {"Genre"}, {"Genre"}),
				    #"Merged Queries4" = Table.NestedJoin(#"Expanded Dim_Genres_View", {"App ID"}, Dim_Platforms_View, {"App ID"}, "Dim_Platforms_View", JoinKind.LeftOuter),
				    #"Expanded Dim_Platforms_View" = Table.ExpandTableColumn(#"Merged Queries4", "Dim_Platforms_View", {"Platform"}, {"Platform"}),
				    #"Merged Queries5" = Table.NestedJoin(#"Expanded Dim_Platforms_View", {"App ID"}, Dim_Publishers_View, {"App ID"}, "Dim_Publishers_View", JoinKind.LeftOuter),
				    #"Expanded Dim_Publishers_View" = Table.ExpandTableColumn(#"Merged Queries5", "Dim_Publishers_View", {"Publisher"}, {"Publisher"})
				in
				    #"Expanded Dim_Publishers_View"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

