table Dim_Applications_View
	lineageTag: 75ec3e75-1e5a-478e-ad42-200f5687fc7e

	column 'App ID'
		dataType: int64
		formatString: 0
		lineageTag: 29815894-d2a0-49e2-860e-05a7259c9d51
		summarizeBy: none
		sourceColumn: App ID

		annotation SummarizationSetBy = Automatic

	column Game
		dataType: string
		lineageTag: cf582ef3-4e86-4df7-a8a3-e16ff6b6ecb6
		summarizeBy: none
		sourceColumn: Game

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 05ed00eb-8ac4-436e-82c1-2283087352ff
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Is Free'
		dataType: string
		lineageTag: 80a69cb2-4787-472c-8f27-e37b504a7464
		summarizeBy: none
		sourceColumn: Is Free

		annotation SummarizationSetBy = Automatic

	column 'Price Category'
		dataType: string
		lineageTag: 2f17bf9f-a00a-4d05-9c91-598e1e6cae31
		summarizeBy: none
		sourceColumn: Price Category

		annotation SummarizationSetBy = Automatic

	partition Dim_Applications_View = m
		mode: import
		source =
				let
				    Source = Sql.Database("DESKTOP-M9MOB75\SQLEXPRESS", "Steam"),
				    dbo_Dim_Applications_View = Source{[Schema="dbo",Item="Dim_Applications_View"]}[Data],
				    #"Capitalized Each Word" = Table.TransformColumns(dbo_Dim_Applications_View,{{"Type", Text.Proper, type text}, {"Is Free", Text.Proper, type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Capitalized Each Word",{"Minimum Graphics", "Required Memory", "Minimum OS", "Minimum Memory", "Minimum Processor", "Required Processor", "Required Graphics", "Required OS"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

